package br.com.estapar.parking.parking.api.dto.event;

import java.time.LocalDateTime;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;

@Schema(description = "DTO representing an event sent by the parking simulator.")
public record ParkingEventDTO(

    @JsonProperty("license_plate")
    @Schema(
            description = "Vehicle license plate.",
            example = "ZUL0001",
            requiredMode = Schema.RequiredMode.REQUIRED
    )
    String licensePlate,

    @Schema(
            description = "Latitude of the parking spot. Only present in PARKED events.",
            example = "-23.561684"
    )
    Double lat,

    @Schema(
            description = "Longitude of the parking spot. Only present in PARKED events.",
            example = "-46.655981"
    )
    Double lng,

    @JsonProperty("entry_time")
    @Schema(
            description = "Entry timestamp. Present only for ENTRY events.",
            example = "2025-01-01T12:00:00"
    )
    LocalDateTime entryTime,

    @JsonProperty("exit_time")
    @Schema(
            description = "Exit timestamp. Present only for EXIT events.",
            example = "2025-01-01T15:30:00"
    )
    LocalDateTime exitTime,

    @JsonProperty("event_type")
    @Schema(
            description = "Type of the event generated by the simulator.",
            example = "ENTRY",
            allowableValues = {"ENTRY", "PARKED", "EXIT"},
            requiredMode = Schema.RequiredMode.REQUIRED
    )
    String eventType
) {}